code-insiders --install-extension aaron-bond.better-comments
code-insiders --install-extension akamud.vscode-theme-onedark
code-insiders --install-extension akmarnafi.comment-headers
code-insiders --install-extension albert.TabOut
code-insiders --install-extension alefragnani.Bookmarks
code-insiders --install-extension anteprimorac.html-end-tag-labels
code-insiders --install-extension bierner.emojisense
code-insiders --install-extension bierner.markdown-checkbox
code-insiders --install-extension bierner.markdown-emoji
code-insiders --install-extension bierner.markdown-preview-github-styles
code-insiders --install-extension bierner.markdown-yaml-preamble
code-insiders --install-extension carlocardella.vscode-filesystemtoolbox
code-insiders --install-extension christian-kohler.path-intellisense
code-insiders --install-extension CoenraadS.bracket-pair-colorizer-2
code-insiders --install-extension DiemasMichiels.emulate
code-insiders --install-extension eamodio.gitlens
code-insiders --install-extension EliverLara.andromeda
code-insiders --install-extension Equinusocio.vsc-community-material-theme
code-insiders --install-extension Equinusocio.vsc-material-theme
code-insiders --install-extension equinusocio.vsc-material-theme-icons
code-insiders --install-extension formulahendry.terminal
code-insiders --install-extension georgewfraser.vscode-javac
code-insiders --install-extension GitHub.vscode-pull-request-github
code-insiders --install-extension GrapeCity.gc-excelviewer
code-insiders --install-extension Gruntfuggly.todo-tree
code-insiders --install-extension henriqueBruno.github-repository-manager
code-insiders --install-extension huizhou.githd
code-insiders --install-extension IBM.output-colorizer
code-insiders --install-extension jeroen-meijer.pubspec-assist
code-insiders --install-extension jspolancor.presentationmode
code-insiders --install-extension letmaik.git-tree-compare
code-insiders --install-extension lostintangent.wikilens
code-insiders --install-extension mechatroner.rainbow-csv
code-insiders --install-extension mhutchie.git-graph
code-insiders --install-extension ms-dotnettools.csharp
code-insiders --install-extension ms-vscode.cmake-tools
code-insiders --install-extension ms-vscode.live-server
code-insiders --install-extension ms-vscode.powershell
code-insiders --install-extension naumovs.color-highlight
code-insiders --install-extension olivertasevski.vscode-space
code-insiders --install-extension OnlyLys.leaper
code-insiders --install-extension ozaki.markdown-github-dark
code-insiders --install-extension pflannery.vscode-versionlens
code-insiders --install-extension PhilHindle.errorlens
code-insiders --install-extension Pivotal.vscode-boot-dev-pack
code-insiders --install-extension Pivotal.vscode-spring-boot
code-insiders --install-extension PKief.material-icon-theme
code-insiders --install-extension quicktype.quicktype
code-insiders --install-extension redhat.fabric8-analytics
code-insiders --install-extension redhat.java
code-insiders --install-extension redhat.vscode-xml
code-insiders --install-extension RedVanWorkshop.explorer-exclude-vscode-extension
code-insiders --install-extension ritwickdey.LiveServer
code-insiders --install-extension ryanluker.vscode-coverage-gutters
code-insiders --install-extension Shan.code-settings-sync
code-insiders --install-extension sndst00m.markdown-github-dark-pack
code-insiders --install-extension stackbreak.comment-divider
code-insiders --install-extension streetsidesoftware.code-spell-checker
code-insiders --install-extension streetsidesoftware.code-spell-checker-spanish
code-insiders --install-extension telesoho.vscode-markdown-paste-image
code-insiders --install-extension tomoki1207.pdf
code-insiders --install-extension tomsaunders.vscode-workspace-explorer
code-insiders --install-extension twxs.cmake
code-insiders --install-extension Tyriar.lorem-ipsum
code-insiders --install-extension usernamehw.errorlens
code-insiders --install-extension VisualStudioExptTeam.vscodeintellicode
code-insiders --install-extension vscjava.vscode-java-debug
code-insiders --install-extension vscjava.vscode-java-dependency
code-insiders --install-extension vscjava.vscode-java-pack
code-insiders --install-extension vscjava.vscode-java-test
code-insiders --install-extension vscjava.vscode-maven
code-insiders --install-extension vscjava.vscode-spring-boot-dashboard
code-insiders --install-extension vscjava.vscode-spring-initializr
code-insiders --install-extension vsls-contrib.codetour
code-insiders --install-extension vsls-contrib.gistfs
code-insiders --install-extension vsls-contrib.gitdoc
code-insiders --install-extension wayou.vscode-todo-highlight
code-insiders --install-extension wenfangdu.snippet-generator
code-insiders --install-extension yzhang.markdown-all-in-one
code-insiders --install-extension zhuangtongfa.material-theme
